apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: neuralgpu
spec:
  selector:
    matchLabels:
      app: neuralgpu
  serviceName: neuralgpu
  podManagementPolicy: "Parallel"
  replicas: 1
  template:
    metadata:
      name: neuralgpu
      labels:
        app: neuralgpu
    spec:
      imagePullSecrets:
      - name: docker2-pull-secret
      containers:
      - name: main
        image: docker2.openai.com/openai/neuralgpu:dev
        imagePullPolicy: Always
        command: ["bash", "-c", "python -u /neural_gpu_trainer.py --nmaps=256 --task=bmul --progressive_curriculum=5; sleep 100000"]
        resources:
          requests:
            cpu: 6
            memory: 10Gi
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: neuralgpu
spec:
  clusterIP: None
  ports:
  - name: ssh
    port: 22222
    targetPort: 22222
  selector:
    app: neuralgpu
